#!/usr/bin/python
def main():
    import sys
    import logging

    from src.parser import WhisperParser
    from src.runtime import evaluate
    from src.util import WRException

    logging.getLogger('src').disabled = True
    parser = WhisperParser()

    input = None
    try:
        _program, file_name = sys.argv
        with open(file_name) as f:
            input = f.read()
            node = parser.parse(input)
            output = evaluate(('call', node, []))
            print output.raw
    except WRException as e:
        sys.stderr.write(e.message)
        exit(1)
    except ValueError as e:
        sys.stderr.write('''Usage:
whisper file
''')
        exit(1)

if __name__ == '__main__':
    main()
